#!/bin/bash

#======== INI VARIABLES ========
# Change these in the INI file

#======== GLOBAL VARIABLES =========
declare -g mrapmpath="/media/fat/Scripts/.MiSTer_Player"
declare -g misterpath="/media/fat"

#======== DEBUG VARIABLES ========
apmquiet="Yes"
apmdebug="No"
apmtrace="No"

#======== LOCAL VARIABLES ========
apmtimeout=60
startupsleep="Yes"
menuonly="Yes"
monitoronly="No"

#========= PARSE INI =========
# Read INI, Check for mount point presence
while ! test -d /media/fat/
do
	sleep 1
	count=`expr $count + 1`
	if test $count -eq 30; then
		echo " Mount timed out!"
      		exit 1
 		fi
done

if [ -f "${misterpath}/Scripts/MiSTer_APM.ini" ]; then
	source "${misterpath}/Scripts/MiSTer_APM.ini"
fi

# Remove trailing slash from paths
for var in mrapmpath misterpath musicPlay mp3Play audioPlay ostPlay; do
	declare -g ${var}="${!var%/}"
done

# This is triggered by MiSTer_APM_on.sh when we're not running in screen saver mode
if [ "${1,,}" == "monitoronly" ]; then
	monitoronly="Yes"
	startupsleep="No"
fi


# This is triggered by MiSTer_APM_on.sh when we're doing initial installation
if [ "${1,,}" == "quickstart" ]; then
	startupsleep="No"
fi


#======== FUNCTIONS ========
function apm_jsmonitor() {
	# Reset trigger file
	echo "" |>/tmp/.APM_Joy_Change
	# Monitor joystick devices for changes
	inotifywait --quiet --monitor --event create --event delete /dev/input/ --outfile /tmp/.APM_Joy_Change &
}


#======== Start ========
# Kill running process
echo $(basename)
echo $(basename -- ${0})
pids=$(pidof -o $$ $(basename -- ${0}))
if [ ! -z "pids" ]; then
	echo -n " Removing other instances of $(basename -- ${0})..."
	kill -9 ${pids} &>/dev/null
	wait ${pids} &>/dev/null
	echo " Done!"
fi

# Kill old activity processes
echo -n " Stopping activity monitoring..."
killall -q -9 MiSTer_APM_Joy.py
killall -q -9 MiSTer_APM_Mouse.sh
killall -q -9 MiSTer_APM_Keyboard.sh
killall -q -9 mpg123
killall -q -9 xxd
kill -9 $(ps | grep "inotifywait" | grep "APM_Joy_Change" | cut --fields=1 --only-delimited --delimiter=' ')
echo " Done!"

# Convert seconds to minutes
apmtimeout=$(echo - | awk -v t=${apmtimeout} '{print t/60}')


#======== DEBUG OUTPUT =========
if [ "${PMtrace,,}" == "yes" ]; then
	echo "********************************************************************************"
	#======== GLOBAL VARIABLES =========
	echo " mrsAPMath: ${mrapmpath}"
	echo " misterpath: ${misterpath}"
	#======== LOCAL VARIABLES ========
	echo " commandline: ${@}"
	echo " apmtimeout: ${apmtimeout}"
	echo " startupsleep: ${startupsleep}"
	echo " menuonly: ${menuonly}"
	echo " monitoronly: ${monitoronly}"
	echo "********************************************************************************"
fi

echo " Starting MiSTer Audio Play Mode..."
# Start monitoring for device changes
if [ "${apmquiet,,}" == "no" ]; then echo -n " Starting joystick change monitor..."; fi
apm_jsmonitor
if [ "${apmquiet,,}" == "no" ]; then echo " Done!"; fi

# Spawn Joystick monitoring process per detected joystick device
shopt -s nullglob
for joystick in /dev/input/js*; do
	echo " Monitoring controller ${joystick}..."
	"${mrapmpath}/MiSTer_APM_Joy.py" "${joystick}" 2>/dev/null &
done
shopt -u nullglob

# Spawn Mouse monitoring process
echo " Monitoring mouse activity..."
"${mrapmpath}/MiSTer_APM_Mouse.sh" 2>/dev/null &

# Spawn Keyboard monitoring per detected keyboard device
for keyboard in $(dmesg --decode --level info --kernel --color=never --notime --nopager | grep -e 'Keyboard' | grep -Eo 'hidraw[0-9]+'); do
	echo " Monitoring keyboard ${keyboard}..."
	"${mrapmpath}/MiSTer_APM_Keyboard.sh" "${keyboard}" 2>/dev/null &
done
# TODO - Detect keyboard device changes

# Startup done
echo " Done!"


# Wait for system startup - clock synchronization
if [ "${startupsleep,,}" == "yes" ]; then
	echo -n " Waiting 60 seconds for system startup..."
	sleep 60
	echo " Done!"
	echo " MiSTer APM enabled!"
	echo " Please wait for startup"
fi

# Reset activity triggers
echo "" |>/tmp/.APM_Joy_Activity
echo "" |>/tmp/.APM_Mouse_Activity
echo "" |>/tmp/.APM_Keyboard_Activity


#======== MAIN LOOP ========
while :; do
	# If we detect a change to connected joysticks:
	# Compare devices and monitoring processes
	# Make lists of what to add and what to stop monitoring
	if [ -s /tmp/.APM_Joy_Change ]; then
		#echo " Device change(s) detected!"
		# Wait for devices to stabilize
		sleep 1
		
		# Init arrays
		declare -a jsdevices=()
		declare -a jsadd=()
		declare -a jsmonitors=()
		declare -a jsdel=()

		# Make a list of all js devices on system
		shopt -s nullglob
		for joystick in /dev/input/js*; do
			jsdevices+=( "${joystick}" )
			jsadd+=( "${joystick}" )
		done
		shopt -u nullglob
		
		if [ "${apmtrace,,}" = "yes" ]; then
			echo "jsdevices: ${jsdevices[@]}"
			echo "jsadd: ${jsadd[@]}"
		fi
		
		# Make a list of all running js monitoring processes' jsdevices - so we don't have to track a list on disk somewhere
		for joystick in $(ps -o args | grep -e 'MiSTer_APM_Joy.py' | grep -oE '/dev/input/js[0-9]' | sort -u); do
			jsmonitors+=( "${joystick}" )
			jsdel+=( "${joystick}" )
		done
		if [ "${apmtrace,,}" = "yes" ]; then
			echo "jsmonitors: ${jsmonitors[@]}"
			echo "jsdel: ${jsdel[@]}"
		fi

		# Make list of additional devices to monitor
		for joystick in ${jsmonitors[@]}; do
			jsadd=( "${jsadd[@]/${joystick}}" )
		done
		jsadd=( "${jsadd[@]//[[:space:]]/}" )

		# Make list of removed devices to stop monitoring
		for joystick in ${jsdevices[@]}; do
			jsdel=( "${jsdel[@]/${joystick}}" )
		done
		jsdel=( "${jsdel[@]//[[:space:]]/}" )
		if [ "${apmtrace,,}" = "yes" ]; then
			echo "jsadd: ${jsadd[@]}"
			echo "jsdel: ${jsdel[@]}"
		fi
		
		# Add newly detected joystick monitoring
		for joystick in ${jsadd[@]}; do
			if [ ! -z "${joystick}" ]; then
				echo -n " Monitoring new joystick: ${joystick}..."
				"${mrapmpath}/MiSTer_APM_Joy.py" "${joystick}" 2>/dev/null &
				echo " Done!"
			fi
		done

		# Stop removed joystick monitoring
		for joystick in ${jsdel[@]}; do
			if [ ! -z "${joystick}" ]; then
				echo -n " Monitoring stopping for joystick: ${joystick}..."
					for otherpid in $(ps -o pid,args | grep -e 'MiSTer_APM_Joy.py' | grep -e "${joystick}" | awk '{ print $1 }'); do
						kill -9 ${otherpid}
						wait ${otherpid} &>/dev/null
					done
				echo " Done!"
			fi
		done

		# Reset trigger
		echo "" |>/tmp/.APM_Joy_Change
	fi

	if [ "${menuonly,,}" == "yes" ]; then # Only start APM from main menu
		# Check if we're at the main menu, wait 1 minute before checking activity
		if [ "$(cat /tmp/CORENAME)" == "MENU" ] && [ "$(/bin/find /tmp/CORENAME -mmin +1)" ]; then
			# Check activity files against timeout
			if [ "$(/bin/find /tmp/.APM_Joy_Activity -mmin +${apmtimeout})" ] && [ "$(/bin/find /tmp/.APM_Mouse_Activity -mmin +${apmtimeout})" ] && [ "$(/bin/find /tmp/.APM_Keyboard_Activity -mmin +${apmtimeout})" ]; then
				# Reset activity triggers
				echo "" |>/tmp/.APM_Joy_Activity
				echo "" |>/tmp/.APM_Mouse_Activity
				echo "" |>/tmp/.APM_Keyboard_Activity

				if [ "${monitoronly,,}" == "no" ] && [ "$(ps aux | grep -v grep | grep -c -e '{update_all.sh}')" == "0" ] && [ "$(ps aux | grep -v grep | grep -c -e '{MiSTer_APM_on.sh}')" == "0" ]; then
					echo " No activity detected for ${apmtimeout} minutes. APM starting..."
					"/media/fat/Scripts/MiSTer_APM_on.sh" start
					echo " Returned from APM."
				fi

				# Reset activity triggers
				echo "" |>/tmp/.APM_Joy_Activity
				echo "" |>/tmp/.APM_Mouse_Activity
				echo "" |>/tmp/.APM_Keyboard_Activity
			fi
		fi
	else
		# Check activity files against timeout
		if [ "$(/bin/find /tmp/.APM_Joy_Activity -mmin +${apmtimeout})" ] && [ "$(/bin/find /tmp/.APM_Mouse_Activity -mmin +${apmtimeout})" ] && [ "$(/bin/find /tmp/.APM_Keyboard_Activity -mmin +${apmtimeout})" ]; then
			# Reset activity triggers
			echo "" |>/tmp/.APM_Joy_Activity
			echo "" |>/tmp/.APM_Mouse_Activity
			echo "" |>/tmp/.APM_Keyboard_Activity

			if [ "${monitoronly,,}" == "no" ] && [ "$(ps aux | grep -v grep | grep -c -e '{update_all.sh}')" == "0" ] && [ "$(ps aux | grep -v grep | grep -c -e '{MiSTer_APM_on.sh}')" == "0" ]; then
				echo " No activity detected for ${apmtimeout} minutes. APM starting..."
				"/media/fat/Scripts/MiSTer_APM_on.sh" start
				echo " Returned from APM."
			fi

			# Reset activity triggers
			echo "" |>/tmp/.APM_Joy_Activity
			echo "" |>/tmp/.APM_Mouse_Activity
			echo "" |>/tmp/.APM_Keyboard_Activity
		fi
	fi
sleep 3
done
