#!/bin/bash
trap "" HUP
trap "" TERM

#======== INI VARIABLES ========
# Change these in the INI file

#======== GLOBAL VARIABLES =========
declare -g mrapmpath="/media/fat/Scripts/.MiSTer_Player"
declare -g misterpath="/media/fat"

#======== DEBUG VARIABLES ========
apmquiet="Yes"

#======== LOCAL VARIABLES ========

#========= PARSE INI =========
# Read INI, Check for mount point presence
while ! test -d /media/fat/
do
	sleep 1
	count=`expr $count + 1`
	if test $count -eq 30; then
		echo " Mount timed out!"
      		exit 1
 		fi
done

if [ -f "${misterpath}/Scripts/MiSTer_APM.ini" ]; then
	source "${misterpath}/Scripts/MiSTer_APM.ini"
fi

# Remove trailing slash from paths
for var in mrapmpath misterpath musicPlay mp3Play audioPlay ostPlay; do
	declare -g ${var}="${!var%/}"
done


#======== Functions ========
function start() {
	#======== Start ========
	echo -n " Starting SAM..."
	${mrapmpath}/MiSTer_APM_MCP &
}

function quickstart() {
	echo -n " Quickstarting SAM..."
	${mrapmpath}/MiSTer_APM_MCP quickstart &
}

function stop() {
	echo -n " Stopping APM MCP..."
	pids=$(pidof MiSTer_APM_MCP)
	if [ ! -z "${pids}" ]; then
		kill -9 ${pids} &>/dev/null
		wait ${pids} &>/dev/null
	fi
	echo " Done!"

	echo -n " Stopping APM..."
	pids=$(pidof MiSTer_APM_on.sh)
	if [ ! -z "${pids}" ]; then
		kill -9 ${pids} &>/dev/null
		wait ${pids} &>/dev/null
	fi
	echo " Done!"
}

# Kill running process
pids=$(pidof -o $$ $(basename -- ${0}))
if [ ! -z "pids" ]; then
	echo -n " Removing other instances of $(basename -- ${0})..."
	kill -9 ${pids} &>/dev/null
	wait ${pids} &>/dev/null
	echo " Done!"
fi

# Kill old activity processes
echo -n " Stopping activity monitoring..."
killall -q -9 MiSTer_APM_Joy.py
killall -q -9 MiSTer_APM_Mouse.sh
killall -q -9 MiSTer_APM_Keyboard.sh
killall -q -9 xxd
kill -9 $(ps aux | grep "inotifywait" | grep "APM_Joy_Change" | cut --fields=2 --only-delimited --delimiter=' ')
echo " Done!"


#======== DEBUG OUTPUT =========
if [ "${apmquiet,,}" == "no" ]; then
	echo "********************************************************************************"
	#======== GLOBAL VARIABLES =========
	echo " mrapmpath: ${mrapmpath}"
	echo " misterpath: ${misterpath}"
	#======== LOCAL VARIABLES ========
	echo " apmtimeout: ${samtimeout}"
	echo " startupsleep: ${startupsleep}"
	echo " menuonly: ${menuonly}"
	echo "********************************************************************************"
fi

# Parse command line
case "${1,,}" in
    start)
        start
        ;;
    quickstart)
    		quickstart
    		;;    	
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo " Usage: /etc/init.d/S94misterapm {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
